---
- name : Ping, install docker and install mysql-server
  hosts: server
  become: yes
  tasks:
    - name: Ping to target server
      ping:
    - name: Install mysql-server and apache
      apt:
        update_cache: yes
        name: 
          - mysql-server
          - apache2
        state: present
    - name : Download docker install script
      shell : "curl -fsSL https://get.docker.com -o get-docker.sh"
    - name : Install docker using script
      shell : "sh get-docker.sh"